/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpo_tp_lightoff_courtel_danjou;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author jules
 */
public class Interface_Graphique extends javax.swing.JFrame {
    Joueur JoueurP;
    Grille plateau;
    Grille grille_jeu = new Grille();
    /**
     * Creates new form Interface_Graphique
     */
    
    public Interface_Graphique() { /*Cette méthode permet une fois la partie 
démarrer de cliquer directement sur les cases de la grille de jeu dans 
l'interface graphique grâce à la méthode "actionListener" et permet de terminer 
la partie(victoire), si la grille de jeu est complétement éteintes de façon 
sychronisée, un message est annoncé à l'utilisateur qu'il a remporté la partie. 
Suite à cela, le bouton "Lancer Partie" est réactiver afin de jouer à nouveau*/ 
        initComponents(); 
        for (int i = 4; i >= 0; i--) {
            for (int j = 0; j < 5; j++) {
                final int x = i;
                final int y = j; 
                
                this.pack();
                CelluleGraphique cellGraph = new CelluleGraphique(grille_jeu.PlateauDeJeu[i][j]);
                panneau_grille.add(cellGraph);
                cellGraph.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                    action(x, y);
                    panneau_grille.repaint();
                    
                    if(grille_jeu.Grilleteinte() == false) {    
                        message.setText("Félicitation, vous avez remporté la partie de LigthOff !!");
                        btn_start.setEnabled(true);
                    }
                    }
                }); 
            }
        }
    } 
    
    public void placerCelluleLumineuse() { /*Cette méthode permet de placer 
aléatoirement des cellules lumineuses allumées dans la grille de jeu éteinte*/ 
        for (int i = 0; i<5; i++){ //ligne 
           for (int j = 0; j<5; j++){ //colonne
                if (Math.random()>0.5){ 
                    grille_jeu.ChangeEtat(i, j);
                }
            }
        }    
    } 

    public void action(int x, int y) {  /*Cette méthode permet de jouer(échanger 
l'état des cellules lumineuses) la case choisie ainsi que celles qui lui sont 
adjacentes*/
        grille_jeu.ChangeEtat(x, y);
        if (x < 5 - 1) {
            grille_jeu.ChangeEtat(x+1, y);
        }
        if (x > 0) {
            grille_jeu.ChangeEtat(x-1, y);
        }
        if (y < 5 - 1) {
            grille_jeu.ChangeEtat(x, y+1);
        }         
        if (y > 0) {
            grille_jeu.ChangeEtat(x, y-1);
        }
    }  
      
    public void initialiserPartie() { /*Cette méthode permet d'initialiser une partie 
avec son interface graphique*/
        this.placerCelluleLumineuse(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jSeparator1 = new javax.swing.JSeparator();
        jColorChooser1 = new javax.swing.JColorChooser();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        panneau_grille = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(720, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(790, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(0, 102, 204));
        panneau_grille.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 672, 672));

        btn_start.setBackground(new java.awt.Color(153, 153, 153));
        btn_start.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        btn_start.setForeground(new java.awt.Color(0, 102, 153));
        btn_start.setText("Lancer Partie");
        btn_start.setBorder(null);
        btn_start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_start.setIconTextGap(5);
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 1, 107, 674));

        message.setColumns(20);
        message.setRows(5);
        jScrollPane1.setViewportView(message);
        message.getAccessibleContext().setAccessibleParent(message);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 780, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 700, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, -1, -1));

        setBounds(0, 0, 794, 711);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        panneau_grille.repaint();
        initialiserPartie();
        message.setText("La grille de jeu est composée de 2 couleurs : jaune pour les cellules allumées & bleue pour celles éteintes. Le but est de l'éteindre entierement.");
        btn_start.setEnabled(false);
    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Graphique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea message;
    private javax.swing.JPanel panneau_grille;
    // End of variables declaration//GEN-END:variables
}
